name: D2 - Deployment on EC2

on:
    push:
        branches:
            -main

    jobs:
        deployment:
            runs-on: ubuntu

            steps:
            - name: Checkout code from github repo
              uses: actions/checkout@v4
