name: D2 - Deployment on EC2

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from github repo
        uses: actions/checkout@v4

      - name: Run some code
        run: |
          whoami
          ls -al
          pwd
